"""add thumbnails and previews

Revision ID: 35e2b70ed3bd
Revises: 0001
Create Date: 2026-07-19 20:42:25.773580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e2b70ed3bd'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('thumbnail_path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('preview_clip_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'preview_clip_path')
    op.drop_column('files', 'thumbnail_path')
    # ### end Alembic commands ###